fsspec dependency: require http extras
otherwise NXOntology.read_node_link_json(url) can raise:
ImportError: HTTPFileSystem requires "requests" and "aiohttp" to be installed